version: '2'
services:
  ubuntu:
    image: ubuntu:latest
    container_name: ubuntu
    command: tail -F netology
  centos7:
    image: centos:7
    container_name: centos7
    command: tail -F netology
